version: '3.9'

services:
  backend:
    build: ./osint-backend
    container_name: osint-backend
    ports:
      - "8082:8082"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - SPRING_PROFILES_ACTIVE=prod

  frontend:
    build: ./osint-frontend
    container_name: osint-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
